### ISSUE TITLE
Select 组件报错 'Encountered two children with the same key `[object Object]`'

### ISSUE THREAD

**Issue by sherry007** [nanxiaobei/ant-plus#11]
#### 问题描述
使用了 ant-plus 的组件 `Select`，其中定义了 data 如下：
```javascript
const mapOptions = map(allMaps, ({ id, name }) => {
    return {
      value: id,
      label: (
        <div>
          <span>{name}</span>
          <span style={{ color: 'rgba(0, 0, 0, 0.32)' }}> · {id}</span>
        </div>
      )
    };
  });

...

return (
 <Form  {...itemLayout} labelAlign="right" onFinish={onFinish}>
   <Select
     labelCol={{ span: 5 }}
     name="id"
     rules={['required']}
     tip="full"
     data={mapOptions}
   />
</Form>
```

因为我的 label 传入的是一个 JSX 元素，所以报错如下：

![image](https://user-images.githubusercontent.com/5960194/81374077-f306fa80-9130-11ea-8160-7bb165595570.png)

我查看了 Select 组件这部分的[源码](https://github.com/nanxiaobei/ant-plus/blob/master/lib/index.jsx)，发现

![image](https://user-images.githubusercontent.com/5960194/81374487-f18a0200-9131-11ea-9448-72d3559c404a.png)

他将 `item[label]` 作为了 Select.Option 的 key 值了，所以是否能修复一下这个问题，个人觉得或许用 `item[value]` 做 key 值比较好，因为他一般情况下是唯一且 primitive 的变量，期待回复！

**Comment by nanxiaobei** [comment]
你好，感谢反馈，`4.0.4` 已更新。
默认使用 `value` 为 `key`，若某些情况下 `value` 不唯一，可在 `data` 中自定义 `key`。

**Comment by sherry007** [comment]
> 你好，感谢反馈，`4.0.4` 已更新。
> 默认使用 `value` 为 `key`，若某些情况下 `value` 不唯一，可在 `data` 中自定义 `key`。

谢谢啦！😄
