### ISSUE TITLE
TextArea 的 label 有问题

### ISSUE THREAD

**Issue by yf-hk** [nanxiaobei/ant-plus#18]
![image](https://github.com/nanxiaobei/ant-plus/assets/203980/65e817a9-422e-4ccd-9ae1-dd541d46a636)
![image](https://github.com/nanxiaobei/ant-plus/assets/203980/da975d80-344d-4ea0-bd60-cdf22cac7fb2)

**Comment by nanxiaobei** [comment]
TextArea 需直接引入：

```js
import { TextArea } from 'antx'
```
