### ISSUE TITLE
写了一个类似的项目

### ISSUE THREAD

**Issue by wangxingkang** [nanxiaobei/ant-plus#4]
我的项目：https://github.com/alitajs/ant-design-plus

**Comment by nanxiaobei** [comment]
不太一样哦~
我的这个是纯针对 Ant Desgin Form 开发封装的，不是提供新的组件。😁

**Comment by wangxingkang** [comment]
嗯嗯  可以互补一下

**Comment by wangxingkang** [comment]
名字一样 哈哈
