### ISSUE TITLE
357行这个样式为何要追加 id ？

### ISSUE THREAD

**Issue by pkaq** [nanxiaobei/ant-plus#7]
`          className={`${className} ${id}`} `
357行这个样式为何要追加 id ？

**Comment by nanxiaobei** [comment]
方便自定义某个表单域样式的需求~

**Comment by pkaq** [comment]
如果我有个表单项id为locked而我又恰好定义了一个叫做locked的样式来控制表格样式 这样会有问题
建议还是保留表单项name的配置

**Comment by nanxiaobei** [comment]
两种不同的类型的变量命名冲突，在编码工作中也不太建议，建议可以修改控制样式的 `locked` 为 `is-locked` 等
