### ISSUE TITLE
autosize is deprecated, please use autoSize instead. 

### ISSUE THREAD

**Issue by anthhub** [nanxiaobei/ant-plus#8]
index.js:1 Warning: [antd: Input.TextArea] autosize is deprecated, please use autoSize instead. 
    in ResizableTextArea (created by Context.Consumer)
    in Context.Consumer (created by TextArea)
    in TextArea (at Detailpanel.jsx:250)
    in Detailpannel (at Editor.jsx:140)
    in Editor (at SlidesTab/​index.jsx:145)
    in Topics (created by Router.Consumer)
    in Router.Consumer (created by withRouter(Topics))
    in withRouter(Topics) (at Lesson.page.tsx:20)
    in Index (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (at App.tsx:18)
    in App (at src/​index.tsx:11)

**Comment by anthhub** [comment]
react 报的warning 希望尽快修复

**Comment by nanxiaobei** [comment]
后面将根据 Ant Desgin 4.0 重构此项目，以适配新版本，目前暂无时间修复现版本 warning，抱歉
